### ISSUE TITLE
Error Message: TypeError: axis() got an unexpected keyword argument 'autoscale'

### ISSUE THREAD

**Issue by qwang12** [maxlit/pyEdgeworthBox#1]
File "c:\python38\lib\site-packages\pyEdgeworthBox\pyEdgeworthBox.py", line 267, in plot
    plt.axis([0,m,0,m],autoscale=False)

  File "c:\python38\lib\site-packages\matplotlib\pyplot.py", line 2461, in axis
    return gca().axis(*args, emit=emit, **kwargs)

  File "c:\python38\lib\site-packages\matplotlib\axes\_base.py", line 1813, in axis
    raise TypeError(f"axis() got an unexpected keyword argument "

TypeError: axis() got an unexpected keyword argument 'autoscale'

**Comment by maxlit** [comment]
What was the code that generated this error?

**Comment by qwang12** [comment]
def plot(self,fname=None):
        plot_endow,=plt.plot(self.IE1[0],self.IE1[1],color="white",marker="o")
        m=max(self.IE[0],self.IE[1])
        plt.axis([0,m,0,m],autoscale=False)

when I replace plt.axis([0,m,0,m],autoscale=False) with plt.axis([0,m,0,m]), the issue is solved. 👍

**Comment by ndharari** [comment]
Hi, issue still up, even with the binder without any modifications. 
Maybe should delete autoscale in the main repo deffinition and then close it!
Thanks for the amazing work

**Comment by mjervelund** [comment]
I have the same issue, I tried the fix about but then I end up with this error, will try to solve it and return with a fix.

```
\python.exe /main.py
\pyEdgeworthBox\pyEdgeworthBox.py:135: RuntimeWarning: divide by zero encountered in double_scalars
  return lambda x,y: u_x(x,y)/u_y(x,y)
\pyEdgeworthBox\pyEdgeworthBox.py:215: RuntimeWarning: invalid value encountered in double_scalars
  self._pareto=lambda x: root(lambda y: _(self.MRS1,x,y)-_(self.MRS2,self.IE[0]-x,self.IE[1]-y),self.Y[0],self.Y[-1]) # Pareto solutions in functional form
Traceback (most recent call last):
  File "\main.py", line 11, in <module>
    EB=eb.EdgeBox(  u1 = lambda x,y: 4*x*x**4
  File "\pyEdgeworthBox\pyEdgeworthBox.py", line 171, in __init__
    self.calc()
  File "\pyEdgeworthBox\pyEdgeworthBox.py", line 177, in calc
    self.calc_pareto()
  File "\pyEdgeworthBox\pyEdgeworthBox.py", line 220, in calc_pareto
    PU1_X=root(lambda x: _(self._pareto,x)-_(self.u_ie_1,x),self.U1_min[0],self.U1_max[0])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by maxlit** [comment]
Project moved to https://gitlab.com/maxlit/pyEdgeworthBox . There this issue is fixed in the new version, docker container added.

**Comment by mjervelund** [comment]
I've setup a pull request to update the readme @ https://github.com/maxlit/pyEdgeworthBox/pull/2 , it might also be worth looking into this https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html to automate the whole process and avoid issues that can arise from people cloning this old codebase.
